export enum NotificationType {
  TOUR_HOT = 'TOUR_HOT',
  TOUR_NEW = 'TOUR_NEW',
  TOUR_DISCOUNTED = 'TOUR_DISCOUNTED',
  TOUR_PENDING_APPROVAL = 'TOUR_PENDING_APPROVAL',
  TOUR_APPROVED = 'TOUR_APPROVED',
  TOUR_REJECTED = 'TOUR_REJECTED',
  TOUR_UPDATED = 'TOUR_UPDATED',
  TOUR_DELETED = 'TOUR_DELETED',
  TOUR_ASSIGNED_TO_GUIDE = 'TOUR_ASSIGNED_TO_GUIDE',
  TOUR_ASSIGNMENT_REMOVED = 'TOUR_ASSIGNMENT_REMOVED',
  TOUR_ASSIGNMENT_UPDATED = 'TOUR_ASSIGNMENT_UPDATED',
  TOUR_AVAILABLE_DATE_COMPLETED = 'TOUR_AVAILABLE_DATE_COMPLETED',
  ARTICLE_HOT = 'ARTICLE_HOT',
  ARTICLE_NEW = 'ARTICLE_NEW',
  ARTICLE_PENDING_APPROVAL = 'ARTICLE_PENDING_APPROVAL',
  ARTICLE_APPROVED = 'ARTICLE_APPROVED',
  ARTICLE_REJECTED = 'ARTICLE_REJECTED',
  ARTICLE_UPDATED = 'ARTICLE_UPDATED',
  ARTICLE_DELETED = 'ARTICLE_DELETED',
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
  ADMIN_BROADCAST = 'ADMIN_BROADCAST',
  CHATBOT_MAJOR_UPDATE = 'CHATBOT_MAJOR_UPDATE',
  CHATBOT_MAINTENANCE_NOTICE = 'CHATBOT_MAINTENANCE_NOTICE',
  CHATBOT_NEW_FEATURE_RELEASED = 'CHATBOT_NEW_FEATURE_RELEASED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_DISPUTED = 'PAYMENT_DISPUTED',
  PROMOTION_UPCOMING = 'PROMOTION_UPCOMING',
  PROMOTION_STARTING = 'PROMOTION_STARTING',
  PROMOTION_ENDING = 'PROMOTION_ENDING',
  PROMOTION_EXPIRED = 'PROMOTION_EXPIRED',
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED_BY_USER = 'BOOKING_CANCELLED_BY_USER',
  BOOKING_CANCELLED_BY_ADMIN = 'BOOKING_CANCELLED_BY_ADMIN',
  BOOKING_RESCHEDULED = 'BOOKING_RESCHEDULED',
  BOOKING_COMPLETED = 'BOOKING_COMPLETED',
  BOOKING_FAILED = 'BOOKING_FAILED',
  BOOKING_TOUR_ASSIGNED_GUIDE = 'BOOKING_TOUR_ASSIGNED_GUIDE',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
  SUPPORT_TICKET_CREATED = 'SUPPORT_TICKET_CREATED',
  SUPPORT_TICKET_UPDATED = 'SUPPORT_TICKET_UPDATED',
  SUPPORT_TICKET_RESOLVED = 'SUPPORT_TICKET_RESOLVED',
  SUPPORT_TICKET_CLOSED = 'SUPPORT_TICKET_CLOSED',
  BOOKMARKED_TOUR_STARTING_SOON = 'BOOKMARKED_TOUR_STARTING_SOON',
}

export enum NotificationChannel {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH = 'PUSH',
  IN_APP = 'IN_APP',
}

export type Notification = {
  id: string;
  type: NotificationType;
  title: string;
  data: Record<string, any>;
  sentVia: NotificationChannel;
  createdAt: string;
  readAt: string | null;
  isRead: boolean;
}

export type NotificationListRequest = {
  type?: NotificationType;
  isRead?: boolean;
  notificationId?: string;
  page: number;
  size: number;
  sortBy?: string;
  order?: 'asc' | 'desc';
}

export type NotificationListResponse = {
  content: Notification[];
  totalElements: number;
  totalPages: number;
  size: number;
  number: number;
}

export type NotificationRecipient = {
  notification: Notification;
  readAt: string | null;
  sentAt: string;
  status: string;
}
